### ISSUE TITLE
disable demo content

### ISSUE THREAD

**Issue by TheRojam** [SimonMueller/grav-theme-pluspunkt#14]
how can i disable the demo content?

**Comment by SimonMueller** [comment]
I think you have to install the theme via the command line. There you can select if you want to use the demo content or not. (screenshot below)

![grafik](https://user-images.githubusercontent.com/2339593/34648266-83a0b76e-f397-11e7-89ea-a90add7cd608.png)

Source: https://learn.getgrav.org/advanced/grav-development#demo-content

**Comment by TheRojam** [comment]
I've already installed this theme. But the question is now, after setup the page with demo content and changed this demo content, how can i disable to install the demo content?
Yesterday after i run your last update i had to reconfigure the page, because the demo content was installed again with the update. 
there was no new question.
Is there any yaml-file? i couldn't find any thin in the system.yaml, site.yaml in user/ or even in config.

**Comment by SimonMueller** [comment]
This is indeed not how I would expect it to be and I am not sure if it is intended or not. I asked in the Grav Slack channel for help but there was no answer that fixed your use case. My guess is that is intended only for development usage and if I wanted to provide demo content i should create a skeleton.

For now you could just install the theme without the demo content and copy the contents of the `_demo`folder into your `user` folder and it should be fixed and it won't be copied over on update...
