### ISSUE TITLE
just an observation

### ISSUE THREAD

**Issue by diomed** [SimonMueller/grav-theme-pluspunkt#18]
when you write stuff in changelog you should actually write it other way 
- from bottom to top - so that newest updates show on top, and oldest on bottom

**Comment by diomed** [comment]
https://github.com/SimonMueller/grav-theme-pluspunkt/blob/25f8f3aa2328e78e7ea4dadffbec3c6dc8726479/templates/partials/footer.html.twig#L17
you have `</br>`  - should just be `<br>`

**Comment by SimonMueller** [comment]
thanks for mentioning this. it indeed increases the readability. i changed it and created a new release...

see: https://github.com/SimonMueller/grav-theme-pluspunkt/tree/1.1.1
