### ISSUE TITLE
Features page error on fresh install

### ISSUE THREAD

**Issue by nigelwhite** [SimonMueller/grav-theme-pluspunkt#22]
Hi. Great theme, thanks.

On fresh install the Features page gives error

RuntimeException (400) Template "features.html.twig" is not defined.

Grav 1.5.10

**Comment by SimonMueller** [comment]
Hi again. Thanks for your feedback!

I am not sure which page you mean by `features.html.twig`. Because the pluspunkt theme does not provide such a page/template.

Could this be a page which you used from another theme?

**Comment by nigelwhite** [comment]
Ah yes, you're right. I hadn't realised. It must be from another theme. Thanks
